### ISSUE TITLE
Implementar a user story US1

### ISSUE THREAD

**Issue by hiago666** [hiago666/TimeNow#11]

**Comment by hiago666** [comment]
https://drive.google.com/file/d/0B33_W8QfqLhtSzNOalYyM1FqTTQ/view?usp=sharing

**Comment by lucas-faria-faria** [comment]
RESULTADO DOS TESTES:
1- na parte de cadastro quando digito a senha errada, volta para tela de login em branco. é interessante ter um alert falando senha errada e aí a pagina da um refresh.
2-depois que cadastrei uma atividade, aparece a confirmação de cadastro mas continua na tela de cadastro de atividade. Após cadastrar atividade tem como redirecionar para a página inicial de atividades recentes?
3- ao excluir atividade não tem confirmação de exclusão.
4- validar criação de atividade com mesmo nome (consegui criar duas atividades iguais).
5- não existe uma confirmação de logout.
6- mesmo após logado a opção cadastrar aparece na parte de cima da tela do lado do nome de usuário.

OBSERVAÇÕES SOBRE DESIGN

1- ao entrar no site (index.php) seria legal colocar uma logo e uma frase e o botão de cadastre-se grande centralizado.
2-depois de efetuar o login na tela inicial aparecer uma mensagem de boas vindas.
3- Acho que podemos trabalhar melhor as cores,fontes e o modelo dos botões e janelas . Pensando em ficar parecido com o GMAIL.  é complicado fazer alterações agora?

**Comment by hiago666** [comment]
Script pra criação do banco de dados local:
Tabela usuários

CREATE TABLE `usuarios` (
  `id_usuario` int(11) NOT NULL AUTO_INCREMENT,
  `nome` varchar(50) COLLATE latin1_general_ci NOT NULL,
  `profissao` varchar(50) COLLATE latin1_general_ci NOT NULL,
  `senha` varchar(50) COLLATE latin1_general_ci NOT NULL,
  `email` varchar(50) COLLATE latin1_general_ci NOT NULL,
  PRIMARY KEY (`id_usuario`)
) ENGINE=MyISAM AUTO_INCREMENT=26 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci

Tabela atividade

CREATE TABLE `atividade` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tempo_investido` int(11) DEFAULT '0',
  `descricao` varchar(100) DEFAULT '0',
  `nome` varchar(50) DEFAULT '0',
  `usuario` varchar(50) DEFAULT '0',
  `hora_registro` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=latin1
