### ISSUE TITLE
PENDÊNCIA - PÓS ENTREGA1

### ISSUE THREAD

**Issue by lucas-faria-faria** [hiago666/TimeNow#15]
PENDÊNCIAS
•	Projeto do Sistema
1.	Na tela inicial do usuário, implementar a tela de boas-vindas;
2.	Tirar a barra de ferramentas superior e somente mostrar até que o usuário faça login.
3.	Retirar da tela implementada os botões do User Stories ainda não implementados.
4.     Padronizar nome dos botões (registrar atividade para nova atividade).
5.     Implementar tela de confirmação genérica para exclusão, logout. ex: deseja realizar essa operação? sim() não()
6.    Passar a ID como foreign key ao invés do e-mail

•	Gerência do Projeto
1.	Para a entrega1 da documentação incluir roteiro de testes manuais, incluir imagem do cronograma de acompanhamento do projetos e tarefas (github).

•	Design e interação
1.	Providenciar a troca da plataforma de prototipação. Axure para pingento e realizar alterações solicitadas pelo usuário:
a)	Na visualização do histórico de atividades, colocar em colunas as semanas anteriores para comparação.
b)	Melhorar usabilidade do site (cores, botões).

•	Validação do Sistema
1.	Criar tela de boas vindas;
2.	Criar Caso de testes do US0 e US1;
3.	Validar alterações no MVC;
4.	Validar consistência do banco de dados após alterações do sistema.

**Comment by thiagonascimento** [comment]
Telas
https://www.dropbox.com/sh/1zvcuywkhs15649/AABf1e0yfiWySwwFL6eXeevCa?dl=0

**Comment by hiago666** [comment]
P/ Thiago, projeto com as telas novas com pau
https://drive.google.com/file/d/0B1-KBeptJHWHU084S1BiQVZ6Vkk/view
