### ISSUE TITLE
ENTREGA3_THIAGO e MATHEUS

### ISSUE THREAD

**Issue by lucas-faria-faria** [hiago666/TimeNow#29]
Implemente uma suíte de testes automatizados (testes de unidades) que certifiquem de
que o que está sendo exibido ao usuário na US6 e US7 está de acordo com a especificação. As
demais partes do sistema devem ser testadas conforme necessário

**Prazo para entrega: 06/05/17 a 25/05/17**

**Comment by thiagonascimento** [comment]
Tela US07 e mlhoria do desgin

https://www.dropbox.com/sh/topryg96p83lo67/AAAdMi7dshjLM2mHLMtQqUona?dl=0
